# For a sample of this file; please refer to the file on the master branch of the repository
# Beware: Do not change the format of this yaml. However you can add/remove the JMeter > Elements list.
JMeter:
  ThreadGroups:
  - ThreadGroup
  - SetupThreadGroup
  - PostThreadGroup
  Elements:
  - AuthManager
  - CookieManager
  - HeaderManager
  - CacheManager
  - CSVDataSet  
  - TransactionController  
  - ConfigTestElement
  - ConstantTimer
  - UniformRandomTimer
  - GaussianRandomTimer
  - Arguments
  - ProxyControl
  - RegexExtractor
  - TestAction
  - BeanShellSampler
  - JSR223Sampler
  - IfController
  - LoopController
  - ResultCollector
  - ResponseAssertion
  - XPath2Assertion
  - JSONPathAssertion
  - DebugSampler
  version: "5.3" #Update the latest version of JMeter