#Do not change the format of this yaml. However you can add/remove the JMeter > Elements list.
JMeter:
  Elements:
  - ResultCollector
  - ResponseAssertion
  - TransactionController
  - CookieManager
  - HeaderManager
  - CacheManager
  - ConfigTestElement
  - RegexExtractor
  - CSVDataSet
  - UniformRandomTimer
  - GaussianRandomTimer
  - DebugSampler
  - Arguments
  version: "5.3"