#Do not change the format of this yaml. However you can add/remove the JMeter > Elements list.
JMeter:
  Elements:
  - ResultCollector
  - ResponseAssertion
  - TransactionController
  - AuthManager
  - CookieManager
  - HeaderManager
  - CacheManager
  - ConfigTestElement
  - RegexExtractor
  - CSVDataSet
  - UniformRandomTimer
  - GaussianRandomTimer
  - DebugSampler
  - Arguments
  - ProxyControl
  - BeanShellSampler
  - JSR223Sampler
  - IfController
  - LoopController
  version: "5.3" #Update the latest version of JMeter