#Do not change the format of this yaml. However you can add/remove the JMeter > Elements list.
JMeter:
  ThreadGroups:
  - ThreadGroup
  - SetupThreadGroup
  - PostThreadGroup
  Elements:
  #NonTest Elements
  - ProxyControl
  #Logic Controllers
  - TransactionController  
  - IfController
  - LoopController
  #Config Elements
  - ConfigTestElement
  - Arguments
  - AuthManager
  - CookieManager
  - HeaderManager
  - CacheManager
  - CSVDataSet
  #Timers
  - ConstantTimer
  - UniformRandomTimer
  - GaussianRandomTimer
  - RegexExtractor
  #Listeners
  - ResultCollector
  - ResponseAssertion
  - XPath2Assertion
  - JSONPathAssertion
  #Samplers
  - TestAction  
  - DebugSampler
  - JSR223Sampler
  - BeanShellSampler
  #Official JMeter Plugins
  Plugins:
    Default:
      - DummySampler
      - UDP
      - SeleniumWebDriver
      - Visualizer
    Custom:
      # Add custom plugin mappings below here (key: value) - for details check README.md

  version: "5.3" #Update the latest version of JMeter