#Do not change the format of this yaml. This is just a back up of the `config.yaml`.
#In case if you misconfigured, you can copy the below structure and paste it in the `config.yaml`.
JMeter:
  ThreadGroups:
  - ThreadGroup
  - SetupThreadGroup
  - PostThreadGroup
  Elements:
  #NonTest Elements
  - ProxyControl
  #Logic Controllers
  - TransactionController  
  - IfController
  - LoopController
  #Config Elements
  - ConfigTestElement
  - Arguments
  - AuthManager
  - CookieManager
  - HeaderManager
  - CacheManager
  - CSVDataSet
  #Timers
  - ConstantTimer
  - UniformRandomTimer
  - GaussianRandomTimer
  - RegexExtractor
  #Listeners
  - ResultCollector
  - ResponseAssertion
  - XPath2Assertion
  - JSONPathAssertion
  #Samplers
  - TestAction  
  - DebugSampler
  - JSR223Sampler
  - BeanShellSampler
  version: "5.3" #Update the latest version of JMeter