#Do not change the format of this yaml. This is just a back up of the `config.yaml`.
#In case if you misconfigured, you can copy the below structure and paste it in the `config.yaml`.
JMeter:
  Elements:
  - AuthManager
  - CookieManager
  - HeaderManager
  - CacheManager
  - CSVDataSet  
  - TransactionController  
  - ConfigTestElement
  - ConstantTimer
  - UniformRandomTimer
  - GaussianRandomTimer
  - Arguments
  - ProxyControl
  - RegexExtractor
  - TestAction
  - BeanShellSampler
  - JSR223Sampler
  - IfController
  - LoopController
  - ResultCollector
  - ResponseAssertion
  - XPath2Assertion
  - JSONPathAssertion
  - DebugSampler
  version: "5.3" #Update the latest version of JMeter